image: python:3.13-alpine

pages:
  stage: deploy
  script:
    - pip install -U -r doc-requirements.txt
    - sphinx-build -b html doc/source public
  artifacts:
    paths:
      - public
  only:
    - master
